### ISSUE TITLE
Remote Control TCP commands How To

### ISSUE THREAD

**Issue by magdesign** [CyrCom/TCPiMap#1]
When running  `./TCPiMap` I get a black screen, think there is no video loaded by default (?).

So I am trying to load a video via tcp commands over` curl -s ` followed by IP and command `curl -s http://192.168.2.100:11999 load_video /media/internal/video/wifisync.mp4 
`
Defined my master computers IP in TCPSettings.xml.
But get connection error output when running  `./TCPiMap` on  Rpi:
```

[notice ] TCPSettings.xml file miss some SERVER_BIS child, with IP and PORT grandchildren !
[notice ] Attempting connection to 192.168.2.145:11999 as SERVER IP:PORT. 
[notice ] TCPSettings.xml file miss some SERVER_BIS child, with IP and PORT grandchildren !
[ error ] ofxTCPClient: setup(): couldn't connect to 192.168.2.145 11999
[notice ] Attempting connection to 192.168.2.145:11999 as SERVER IP:PORT. 
[notice ] TCPSettings.xml file miss some SERVER_BIS child, with IP and PORT grandchildren !
[ error ] ofxTCPClient: setup(): couldn't connect to 192.168.2.145 11999
```
Also tried with disabled firewall.
Do I need to run PD on the master computer and if yes with which snippet...

**Can you please describe how to use your mapping tool resp, the remote tcp commands.**

I am very interested in your tool and your coding skills!
Thanks.

**Comment by CyrCom** [comment]
Hello !
I'll try to take a look as soon as I can.
I'm not sure I could resolve it though, because it's been a long time I
didn't use it.
Note that I was using Pure Data as a TCP server.

**Comment by magdesign** [comment]
Thanks for looking into this. 
Just to get a better understanding, you run PD on Raspberry as a TCP server with the Ip of the localhost and a PD instance on your laptop ?

**Comment by CyrCom** [comment]
The Tcp server is on the laptop with PD.
I'm gonna pass you the patch when I get home. You'll gain a lot of time

**Comment by CyrCom** [comment]
Ok here is the patch I used (uploaded on the github page). I am sorry I didn't put much comments on the
patch, I hope you'll find the way to use it.
I still hope to find time to make it usable for someone else than me but
this has not been done yet. But for some basic use, I'm sure you can find a
way how to benefit of this.
I was actually waiting for raspberry 4 and then for openframework to be
compatible... And I switched to other things...
~~ I use PD Vanilla <http://msp.ucsd.edu/software.html> ~~
** EDIT: I used Purr Data !
https://github.com/jonwwilkes/purr-data/releases/
Some externals you can find in uploaded 'TCPiMap-tools.zip'. **
, tell me if you miss some externals when you open the patch (saying 'could not create...')
So basically you can try to open this file "ctl.pd".
Try clicking the green NEXT button, it should send a bunch of commands on
its own.
It should show a 'client' line with some name, socket and IP in the pd
patch. if you set the server's IP right in the TCPSettings.xml.
Be sure to have the box attached to it checked. (it won't work if you don't
get to this step, otherwise tell me)
Click NEXT again and it will load another cue file, try it again to see
some changes on the RPI. there is a 'reload _INIT_' button when you're lost.
Those corresponds to text files in the /cuelist/ folder
At some point try open the subpatch 'mouse and keyboard' you should find
how to control a bit more.
I hope you understand some of the stuff...
also note that the program will work with videos that are placed on the
designated folder (../bin/data/videos if I remember correctly)

I made explanations quickly and it's been almost a long time I didn't look
at that, but I'll try to guide you if you want to try some more stuff.
I remember you were trying to achieve some stuff with mapping too ! I'm
glad you're still going on. Are you working on the RPI 4 ?

Le mer. 5 févr. 2020 à 15:13, Cyril Communal <cyril.communal@gmail.com> a
écrit :

**Comment by magdesign** [comment]
Thanks for uploading the patch.
Tried to run it, but still stuck in some errors:

1.) Puredate is missing some things,
```
 until_delay 100... couldn't create
 time_filter 10... couldn't create
 ftos... couldn't create
 cursor... couldn't create
```

 tried to install with `Find externals => maxlib, zexy, ext13 flatspace`, without luck.


2.) On Rpi side `./TCPi` can not find server and displays a black screen:
```
ofxTCPClient: setup(): couldn't connect to 192.168.2.145 11999
[notice ] Attempting connection to 192.168.2.145:11999 as SERVER IP:PORT. 
[notice ] TCPSettings.xml file miss some SERVER_BIS child, with IP and PORT grandchildren !
```

3.) Do I have to enabled experimental openGL driver on RPi?. 

See screenshot with the errors:

![error](https://user-images.githubusercontent.com/5273166/73923393-1bc9ea80-48cb-11ea-9de5-096cd39dcd9f.png)

Yes, still doing some mapping stuff: https://www.openmapper.ch 
(not enough hw acceleration support on RPi to run smooth, that's why I am very interessted in your solution).

BTW. we are communicating here over public github issue, not email :)

**Comment by CyrCom** [comment]
I think I was wrong saying that I used Pd Vanilla, it is obviously better looking in Purr Data...
https://github.com/jonwwilkes/purr-data/releases/
Yes it is normal you have a black screen, the program starts empty.
You don't have to use the experimental driver.
You are missing the 'server' object so that's why it's not happening.
I gathered the externals you miss in 'TCPiMap-tools.zip'. unzip next to the ctl.pd patch
Let's try it again !

**Comment by magdesign** [comment]
Forgot to mention that I am on Ubuntu 18.04 LTS.
There are no releases for jonwwilkes/purr-data version, so I built pd 0.50-2 and now searching all the missing things to copy by hand to the folder.
found so far: `ftos => ext13 external`

from which external did you get: 
`time_filter`
`netserver`
`cursor`
?

```
 netserver 11999
... couldn't create
 time
... couldn't create
canvas: no method for 'dropdown'
video_list 8 0 7 1 (message->tgl) connection failed
video_list 13 0 0 0 (text->send) connection failed
 legacy_mousemotion
... couldn't create
 legacy_mousewheel
... couldn't create
 legacy_mouseclick
... couldn't create
```

**Comment by magdesign** [comment]
Edit:
I made a windows computer and could successfully run your PureData patch.
The Rpi did connect with the server.
Wow, its quite impressive what you built !!!

However, now I am stuck in how to see/send the mouse to the Rpi.

**Comment by CyrCom** [comment]
Check the file TCPiMap-tools.zip I uploaded, there should be everything needed for this program !
Some of them are my own abstractions.
I don't remember why, but it seems you have to press the wheel (hold click with it) in order to send position... Arguable. Try it
Mouse might not be drawn on the RPi, but quite easy to program if needed

**Comment by magdesign** [comment]
Great!
The idea is to run the your Openframeworks TCPiMap on the RPi but remote control it from a website running on RPi instead of using Puredata. Do you think its possible to code something like this?

Currently I am using [PiMapper](https://github.com/kr15h/ofxPiMapper) and then remote control it with some fake keyboard scripts, but the mouse must be still connected to the RPI, which is a bit ugly. Being able to remote map would be amazing.

Are you interested in working out something, it will be opensourced but implemented in the [PocketVJ](https://www.pocketvj.com/).
Can organize some budget, not millions but the money I gain with selling SD cards will be re-invested  into projects like this ;-)

Let me know and we can discuss further via email.

BTW.
Still using RPi3b+, RPi4 is not usable, spent too many hours on it, its not worth it.

**Comment by CyrCom** [comment]
but why does it have to be a website ? Why not a crossplatform program made
with openframework ? There almost all advantages possible.
I also was thinking of a website remote first but there was so many
blocking issues.
My PD remote was meant to try out before making a OF nice program, that
would really communicate well (OF to OF)

**Comment by magdesign** [comment]
If its "easier" we can go with an Openframeworks App.

The thing is that the webserver is already there and it works with every device, e.g. win, osx, linux, android, ios,... But I see the point with user permissions etc.

**Comment by CyrCom** [comment]
I think the first question is how many people needs the remote control ?
If it's a few people that can spend less than 5 minutes installing an app,
then it's definitely worth it because of the responsiveness and the
possibilities with OF to OF communication.
Also I tried to see with webpage and it smells trouble with all the plugins
and frameworks you need to use and learn to translate from html Java css
elektron pipe Tcp  etc... To finally OF that you need to rewrite in order
to work... And the community is not gonna help when it's very specific like
this. It's better to also develop in the OF <> OF way I figured out.

I would be glad to work something out of the year I spend doing this, we
should discuss it. I have a little bit of free time, I'm a French
'Intermittent' so part of my time is tech on shows and then more or less
free time.
Where do you live ? I thought I remembered you are in Swiss ?

**Comment by magdesign** [comment]
Contacted you via email.

**Comment by magdesign** [comment]
wrote to your gmail account...hope you got it...
